.TH fluid\-nexus 1 2011\-08\-07
.SH NAME
fluid\\-nexus \- PyQt4 application that enables one to share messages and data independent of centralized data networks
.SH SYNOPSIS
.B fluid\-nexus  [options]
.SH DESCRIPTION
Fluid Nexus is an application for Android phones and desktop computers that exchanges messages without the need for centralized mobile networks. Messages hop from one device to another, being transferred by short\-range networking technologies like bluetooth, as well as via the movement of people from one location to another.  For more information see http://fluidnexus.net.
.SH OPTIONS
.TP
.B \-\-version
show program's version number and exit
.TP
.B \-h, \-\-help
show this help message and exit
.TP
.B \-v, \-\-verbose
How verbose to be.  Use up to 3 v's for full debug.
.SH AUTHORS
.B fluid\-nexus was written by Nicholas Knouf <fluidnexus@fluidnexus.net>.
.SH DISTRIBUTION
The latest version of fluid\-nexus may be downloaded from
.UR http://fluidnexus.net
.UE
