# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FluidNexusDesktop.ui'
#
# Created: Sun Oct 17 16:29:37 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FluidNexus(object):
    def setupUi(self, FluidNexus):
        FluidNexus.setObjectName("FluidNexus")
        FluidNexus.resize(400, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/fluid_nexus_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FluidNexus.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(FluidNexus)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.incomingTab = QtGui.QWidget()
        self.incomingTab.setObjectName("incomingTab")
        self.verticalLayout = QtGui.QVBoxLayout(self.incomingTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.incomingMessageText = QtGui.QPlainTextEdit(self.incomingTab)
        self.incomingMessageText.setReadOnly(True)
        self.incomingMessageText.setObjectName("incomingMessageText")
        self.gridLayout_2.addWidget(self.incomingMessageText, 1, 0, 1, 1)
        self.incomingMessagesList = QtGui.QTreeWidget(self.incomingTab)
        self.incomingMessagesList.setObjectName("incomingMessagesList")
        self.gridLayout_2.addWidget(self.incomingMessagesList, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.incomingTab, "")
        self.outgoingTab = QtGui.QWidget()
        self.outgoingTab.setObjectName("outgoingTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.outgoingTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.outgoingMessageText = QtGui.QPlainTextEdit(self.outgoingTab)
        self.outgoingMessageText.setReadOnly(True)
        self.outgoingMessageText.setObjectName("outgoingMessageText")
        self.gridLayout_3.addWidget(self.outgoingMessageText, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.newMessageButton = QtGui.QToolButton(self.outgoingTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.newMessageButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon32x32/icons/32x32/menu_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newMessageButton.setIcon(icon1)
        self.newMessageButton.setIconSize(QtCore.QSize(32, 32))
        self.newMessageButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.newMessageButton.setAutoRaise(True)
        self.newMessageButton.setObjectName("newMessageButton")
        self.horizontalLayout_3.addWidget(self.newMessageButton)
        self.toggleOutgoingButton = QtGui.QToolButton(self.outgoingTab)
        self.toggleOutgoingButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.toggleOutgoingButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon32x32/icons/32x32/menu_enable_outgoing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleOutgoingButton.setIcon(icon2)
        self.toggleOutgoingButton.setIconSize(QtCore.QSize(32, 32))
        self.toggleOutgoingButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toggleOutgoingButton.setAutoRaise(True)
        self.toggleOutgoingButton.setObjectName("toggleOutgoingButton")
        self.horizontalLayout_3.addWidget(self.toggleOutgoingButton)
        self.deleteOutgoingButton = QtGui.QToolButton(self.outgoingTab)
        self.deleteOutgoingButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.deleteOutgoingButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon32x32/icons/32x32/menu_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteOutgoingButton.setIcon(icon3)
        self.deleteOutgoingButton.setIconSize(QtCore.QSize(32, 32))
        self.deleteOutgoingButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.deleteOutgoingButton.setAutoRaise(True)
        self.deleteOutgoingButton.setObjectName("deleteOutgoingButton")
        self.horizontalLayout_3.addWidget(self.deleteOutgoingButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.outgoingMessagesList = QtGui.QTreeWidget(self.outgoingTab)
        self.outgoingMessagesList.setObjectName("outgoingMessagesList")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon32x32/icons/32x32/menu_enable_outgoing.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.outgoingMessagesList.headerItem().setIcon(1, icon4)
        self.gridLayout_3.addWidget(self.outgoingMessagesList, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.outgoingTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        FluidNexus.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FluidNexus)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        FluidNexus.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(FluidNexus)
        self.statusbar.setObjectName("statusbar")
        FluidNexus.setStatusBar(self.statusbar)
        self.actionNewMessage = QtGui.QAction(FluidNexus)
        self.actionNewMessage.setIcon(icon1)
        self.actionNewMessage.setObjectName("actionNewMessage")
        self.actionQuit = QtGui.QAction(FluidNexus)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(FluidNexus)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDelete = QtGui.QAction(FluidNexus)
        self.actionDelete.setIcon(icon3)
        self.actionDelete.setObjectName("actionDelete")
        self.menuFile.addAction(self.actionNewMessage)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(FluidNexus)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.newMessageButton, QtCore.SIGNAL("clicked()"), FluidNexus.showNewMessageWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), FluidNexus.mainWindowDestroyed)
        QtCore.QObject.connect(self.outgoingMessagesList, QtCore.SIGNAL("clicked(QModelIndex)"), FluidNexus.outgoingMessageClicked)
        QtCore.QObject.connect(self.outgoingMessagesList, QtCore.SIGNAL("clicked(QModelIndex)"), FluidNexus.outgoingMessageItemActivated)
        QtCore.QObject.connect(self.deleteOutgoingButton, QtCore.SIGNAL("clicked()"), FluidNexus.deleteOutgoingMessage)
        QtCore.QObject.connect(self.incomingMessagesList, QtCore.SIGNAL("clicked(QModelIndex)"), FluidNexus.incomingMessageClicked)
        QtCore.QObject.connect(self.toggleOutgoingButton, QtCore.SIGNAL("clicked()"), FluidNexus.toggleOutgoingMessage)
        QtCore.QObject.connect(self.outgoingMessagesList, QtCore.SIGNAL("doubleClicked(QModelIndex)"), FluidNexus.outgoingMessageDoubleClicked)
        QtCore.QMetaObject.connectSlotsByName(FluidNexus)

    def retranslateUi(self, FluidNexus):
        FluidNexus.setWindowTitle(QtGui.QApplication.translate("FluidNexus", "Fluid Nexus", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingMessagesList.headerItem().setText(0, QtGui.QApplication.translate("FluidNexus", "Hash", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingMessagesList.headerItem().setText(1, QtGui.QApplication.translate("FluidNexus", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingMessagesList.headerItem().setText(2, QtGui.QApplication.translate("FluidNexus", "Message", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.incomingTab), QtGui.QApplication.translate("FluidNexus", "Incoming", None, QtGui.QApplication.UnicodeUTF8))
        self.newMessageButton.setText(QtGui.QApplication.translate("FluidNexus", "New Message", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleOutgoingButton.setText(QtGui.QApplication.translate("FluidNexus", "Toggle Outgoing", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteOutgoingButton.setText(QtGui.QApplication.translate("FluidNexus", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.outgoingMessagesList.headerItem().setText(0, QtGui.QApplication.translate("FluidNexus", "Hash", None, QtGui.QApplication.UnicodeUTF8))
        self.outgoingMessagesList.headerItem().setText(2, QtGui.QApplication.translate("FluidNexus", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.outgoingMessagesList.headerItem().setText(3, QtGui.QApplication.translate("FluidNexus", "Message", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outgoingTab), QtGui.QApplication.translate("FluidNexus", "Outgoing", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("FluidNexus", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("FluidNexus", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewMessage.setText(QtGui.QApplication.translate("FluidNexus", "New message", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewMessage.setToolTip(QtGui.QApplication.translate("FluidNexus", "Create new message", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("FluidNexus", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("FluidNexus", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("FluidNexus", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setToolTip(QtGui.QApplication.translate("FluidNexus", "Delete Message", None, QtGui.QApplication.UnicodeUTF8))

import FluidNexus_rc
