# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FluidNexusDesktop.ui'
#
# Created: Fri Oct 15 13:08:56 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FluidNexus(object):
    def setupUi(self, FluidNexus):
        FluidNexus.setObjectName("FluidNexus")
        FluidNexus.resize(400, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/fluid_nexus_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FluidNexus.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(FluidNexus)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.incomingTab = QtGui.QWidget()
        self.incomingTab.setObjectName("incomingTab")
        self.verticalLayout = QtGui.QVBoxLayout(self.incomingTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.incomingMessageText = QtGui.QPlainTextEdit(self.incomingTab)
        self.incomingMessageText.setReadOnly(True)
        self.incomingMessageText.setObjectName("incomingMessageText")
        self.gridLayout_2.addWidget(self.incomingMessageText, 1, 0, 1, 1)
        self.incomingMessagesList = QtGui.QTreeWidget(self.incomingTab)
        self.incomingMessagesList.setObjectName("incomingMessagesList")
        self.gridLayout_2.addWidget(self.incomingMessagesList, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.incomingTab, "")
        self.outgoingTab = QtGui.QWidget()
        self.outgoingTab.setObjectName("outgoingTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.outgoingTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.outgoingTab)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_3.addWidget(self.plainTextEdit_2, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolButton = QtGui.QToolButton(self.outgoingTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon32x32/icons/32x32/menu_enable_outgoing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_3.addWidget(self.toolButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.outgoingMessagesList = QtGui.QTreeWidget(self.outgoingTab)
        self.outgoingMessagesList.setObjectName("outgoingMessagesList")
        self.gridLayout_3.addWidget(self.outgoingMessagesList, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.outgoingTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        FluidNexus.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FluidNexus)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        FluidNexus.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(FluidNexus)
        self.statusbar.setObjectName("statusbar")
        FluidNexus.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(FluidNexus)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        FluidNexus.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionNewMessage = QtGui.QAction(FluidNexus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon32x32/icons/32x32/menu_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewMessage.setIcon(icon2)
        self.actionNewMessage.setObjectName("actionNewMessage")
        self.actionQuit = QtGui.QAction(FluidNexus)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionNewMessage)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionNewMessage)

        self.retranslateUi(FluidNexus)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.incomingMessagesList, QtCore.SIGNAL("clicked(QModelIndex)"), FluidNexus.incomingMessageClicked)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), FluidNexus.close)
        QtCore.QMetaObject.connectSlotsByName(FluidNexus)

    def retranslateUi(self, FluidNexus):
        FluidNexus.setWindowTitle(QtGui.QApplication.translate("FluidNexus", "Fluid Nexus", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingMessagesList.headerItem().setText(0, QtGui.QApplication.translate("FluidNexus", "Hash", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingMessagesList.headerItem().setText(1, QtGui.QApplication.translate("FluidNexus", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingMessagesList.headerItem().setText(2, QtGui.QApplication.translate("FluidNexus", "Message", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.incomingTab), QtGui.QApplication.translate("FluidNexus", "Incoming", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("FluidNexus", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.outgoingMessagesList.headerItem().setText(0, QtGui.QApplication.translate("FluidNexus", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.outgoingMessagesList.headerItem().setText(1, QtGui.QApplication.translate("FluidNexus", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.outgoingMessagesList.headerItem().setText(2, QtGui.QApplication.translate("FluidNexus", "Message", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outgoingTab), QtGui.QApplication.translate("FluidNexus", "Outgoing", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("FluidNexus", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("FluidNexus", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewMessage.setText(QtGui.QApplication.translate("FluidNexus", "New message", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewMessage.setToolTip(QtGui.QApplication.translate("FluidNexus", "Create new message", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("FluidNexus", "Quit", None, QtGui.QApplication.UnicodeUTF8))

import FluidNexus_rc
